# Generated by Django 4.2.8 on 2024-05-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0008_alter_shippingaddress_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='contact',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
